language: python
os: linux
notifications:
  email:
    on_success: change

jobs:
  include:
    - stage: "test"
      name: "3.6"
      python: "3.6"
      install:
        - pip install -r requirements.txt
      script:
        - ./test/run_integration_test.sh
