language: python
python:
  - "3.6"
after_success:
  - python -m twine upload dist/* -u semi-technologies -p $PYPIPASS
install:
  - python -m pip install --upgrade pip setuptools wheel
  - python -m pip install tqdm
  - python -m pip install --user --upgrade twine
  - pip install -r requirements.txt
branches: 
  only: 
    - master
dist: xenial
script: 
  - find . -iname "*.py" | xargs pylint --rcfile=.pylintrc
  - python setup.py bdist_wheel
sudo: required