sudo: required
language: python
python:
  - "3.6"
dist: xenial
branches:
  only:
    - master
install:
  - pip3 install -r requirements.txt
  - sudo ln -s $(pwd)/bin/weaviate-cli /usr/local/bin/weaviate-cli
script:
  - weaviate-cli --help
