after_success:
  # Login to dockerhub
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - |
  #   # Build & Push docker images on dev and master
  #   if [ $TRAVIS_PULL_REQUEST = "false" ]; then
  #     if [ $TRAVIS_BRANCH = "master" ]; then
  #       # collect the latest version
  #       LATESTVERSION=$(git show --oneline HEAD:$WEAVIATESCHEMAFILE | jq -r ".info.version")
  #       # Build master
  #       DOCKERTARGET=weaviate_base     
  #     elif [ $TRAVIS_BRANCH = "develop" ]; then
  #       # collect the latest version
  #       LATESTVERSION=unstable
  #       # Build master
  #       DOCKERTARGET=development
  #     fi
  #     # Build & Push
  #     travis_wait 30 docker build -f "Dockerfile-prod" -t creativesoftwarefdn/weaviate:$LATESTVERSION --target $DOCKERTARGET .
  #     docker push creativesoftwarefdn/weaviate:unstable
  #   fi
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
branches: 
  only: 
    - master
    - develop
dist: xenial
script: 
  - find . -iname "*.py" | xargs pylint --rcfile=.pylintrc
sudo: required