name: Build and Publish

on:
  release:
    types: [created]

jobs:
  gh-release:
      name: Create a GitHub Release on new tags
      if: startsWith(github.ref, 'refs/tags')
      runs-on: ubuntu-latest
      steps:
        - name: Download build artifact to append to release
          uses: actions/download-artifact@v4
          with:
            name: weaviate-python-client-wheel
            path: dist
        - name: Release
          uses: softprops/action-gh-release@v1
          with:
            generate_release_notes: true
            draft: true
            files: dist/*.whl
  publish:
    runs-on: ubuntu-latest
    needs: [gh-release]
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Set up Python 3.11
          uses: actions/setup-python@v5
          with:
            python-version: "3.11"
            cache: 'pip' # caching pip dependencies
        - name: Install dependencies
          run: pip install -r requirements-dev.txt
        - name: Build a binary wheel
          run: python -m build
        - name: Publish distribution 📦 to PyPI on new tags
          if: startsWith(github.ref, 'refs/tags')
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            verbose: true
            password: ${{ secrets.PYPI_API_TOKEN }}